# Generated by Django 5.1.1 on 2024-09-13 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0002_beneficiary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beneficiary',
            old_name='bene_id',
            new_name='beneId',
        ),
    ]
