# Generated by Django 5.1.1 on 2024-09-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0005_rename_bankaccount_beneficiary_bank_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='phone',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
